package com.jorgeortizesc.acc;

/***
 * The interface IAccListener provides one method for receiving accelerometer
 * events.
 */
public interface IAccListener {
	/***
	 * Handles an event generated by an accelerometer.
	 *
	 * @param event
	 *            Generated event
	 */
	public void receiveAccEvent(AccEvent event);

}
